/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CheckersJNI */

#ifndef _Included_CheckersJNI
#define _Included_CheckersJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CheckersJNI
 * Method:    getBoardState
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_CheckersJNI_getBoardState
  (JNIEnv *, jobject);

/*
 * Class:     CheckersJNI
 * Method:    getBoardSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CheckersJNI_getBoardSize
  (JNIEnv *, jobject);

/*
 * Class:     CheckersJNI
 * Method:    movePiece
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_CheckersJNI_movePiece
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     CheckersJNI
 * Method:    getBoardValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_CheckersJNI_getBoardValue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CheckersJNI
 * Method:    getCurrentPlayer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CheckersJNI_getCurrentPlayer
  (JNIEnv *, jobject);

/*
 * Class:     CheckersJNI
 * Method:    getSelectedCol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CheckersJNI_getSelectedCol
  (JNIEnv *, jobject);

/*
 * Class:     CheckersJNI
 * Method:    getSelectedRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CheckersJNI_getSelectedRow
  (JNIEnv *, jobject);

/*
 * Class:     CheckersJNI
 * Method:    setSelectedCol
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CheckersJNI_setSelectedCol
  (JNIEnv *, jobject, jint);

/*
 * Class:     CheckersJNI
 * Method:    setSelectedRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CheckersJNI_setSelectedRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     CheckersJNI
 * Method:    isPieceSelected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CheckersJNI_isPieceSelected
  (JNIEnv *, jobject);

/*
 * Class:     CheckersJNI
 * Method:    setPieceSelected
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CheckersJNI_setPieceSelected
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
