/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class domain_CheckersJNI */

#ifndef _Included_domain_CheckersJNI
#define _Included_domain_CheckersJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     domain_CheckersJNI
 * Method:    getBoardState
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_domain_CheckersJNI_getBoardState
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    getBoardSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_domain_CheckersJNI_getBoardSize
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    movePiece
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_domain_CheckersJNI_movePiece
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     domain_CheckersJNI
 * Method:    getBoardValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_domain_CheckersJNI_getBoardValue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     domain_CheckersJNI
 * Method:    getCurrentPlayer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_domain_CheckersJNI_getCurrentPlayer
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    setCurrentPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_setCurrentPlayer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     domain_CheckersJNI
 * Method:    setBoardValue
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_setBoardValue
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     domain_CheckersJNI
 * Method:    getSelectedCol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_domain_CheckersJNI_getSelectedCol
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    getSelectedRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_domain_CheckersJNI_getSelectedRow
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    setSelectedCol
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_setSelectedCol
  (JNIEnv *, jobject, jint);

/*
 * Class:     domain_CheckersJNI
 * Method:    setSelectedRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_setSelectedRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     domain_CheckersJNI
 * Method:    isCellSelected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_domain_CheckersJNI_isCellSelected
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    setCellSelected
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_setCellSelected
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     domain_CheckersJNI
 * Method:    setFromRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_setFromRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     domain_CheckersJNI
 * Method:    setFromCol
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_setFromCol
  (JNIEnv *, jobject, jint);

/*
 * Class:     domain_CheckersJNI
 * Method:    setToCol
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_setToCol
  (JNIEnv *, jobject, jint);

/*
 * Class:     domain_CheckersJNI
 * Method:    setToRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_setToRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     domain_CheckersJNI
 * Method:    getFromRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_domain_CheckersJNI_getFromRow
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    getFromCol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_domain_CheckersJNI_getFromCol
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    getToCol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_domain_CheckersJNI_getToCol
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    getToRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_domain_CheckersJNI_getToRow
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    gameFinished
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_domain_CheckersJNI_gameFinished
  (JNIEnv *, jobject);

/*
 * Class:     domain_CheckersJNI
 * Method:    resetGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_domain_CheckersJNI_resetGame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
